name: Python Package Release

on:
  push:
    # Trigger the workflow only when a tag is pushed
    # The tag must be in the format 'v1.0.0' for example
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the GitHub Actions interface
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    # Condition to ensure the action only runs on a tag push
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.12"

      - name: Install dependencies and build tools
        # Install pip, wheel, and setuptools for package building
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build sdist and wheel
        # Use 'build' to create the .tar.gz and .whl files in 'dist/'
        run: python -m build

      - name: Create GitHub Release
        # Creates the release on GitHub
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # The version is the name of the tag (e.g., v1.0.0)
          tag_name: ${{ github.ref_name }}
          # Defines the release title
          name: Release ${{ github.ref_name }}
          # Defines the release as a draft for review (optional)
          # draft: true
          # Uploads the files from the 'dist/' directory as release assets
          files: dist/*
        env:
          # The GITHUB_TOKEN is automatically injected by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
